'use strict';
const $=id=>document.getElementById(id), canvas=$('scene'), ctx=canvas.getContext('2d');
const WORDS=[
 ['cat','кошка','кошка','f','🐱'],['ball','мяч','мяч','m','⚽'],['book','книга','книга','f','📕'],['phone','телефон','телефон','m','📱'],['basket','корзина','корзина','f','🧺'],['pencil','карандаш','карандаш','m','✏️'],['chocolate','шоколад','шоколад','m','🍫'],['rabbit','кролик','кролик','m','🐰'],['dog','собака','собака','f','🐶'],['apple','яблоко','яблоко','n','🍎'],['flower','цветок','цветок','m','🌼'],['toy','игрушка','игрушка','f','🧸'],['car','машинка','машинка','f','🚗'],['kite','воздушный змей','воздушный змей','m','🪁'],['fish','рыбка','рыбка','f','🐟'],['bird','птичка','птичка','f','🐦'],['banana','банан','банан','m','🍌'],['orange','апельсин','апельсин','m','🍊'],['cake','торт','торт','m','🎂'],['hat','шляпа','шляпа','f','👒'],['bag','сумка','сумка','f','🎒'],['cup','чашка','чашка','f','☕'],['umbrella','зонт','зонт','m','☂️'],['guitar','гитара','гитара','f','🎸']
];
const PRONOUNS=['his','her','their','my','our','your'];
const RU={his:['его','его','его'],her:['её','её','её'],their:['их','их','их'],my:['мой','моя','моё'],our:['наш','наша','наше'],your:['твой','твоя','твоё']};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function makeRound(){
 const counts=shuffle([1,1,1,1,1,1,1,2,2,2,2,2]),words=shuffle(WORDS).slice(0,12);
 const singles=shuffle(['his','her','my','your','his','her','your']),pairs=shuffle(['their','our','their','our','their']);
 return words.map((w,i)=>{const count=counts[i],pronoun=(count===1?singles:pairs).pop();const girl=pronoun==='her'||(pronoun!=='his'&&Math.random()<.5);const child=count===2?2+Math.floor(Math.random()*2):(girl?1:0);const possessive=RU[pronoun][['m','f','n'].indexOf(w[3])];let russian,english;
 if(Math.random()<.5){russian=`Это ${possessive} ${w[1]}.`;english=`This is __ ${w[0]}.`;}else{const adj=['m','f','n'].indexOf(w[3]);russian=`${possessive[0].toUpperCase()+possessive.slice(1)} ${w[2]} ${['красивый','красивая','красивое'][adj]}.`;english=`__ ${w[0]} is beautiful.`;}
 return {count,word:w,pronoun,child,russian,english,choices:shuffle([pronoun,...shuffle(PRONOUNS.filter(p=>p!==pronoun)).slice(0,2)])};});
}
const stumpPositions=[[505,265],[775,365],[1040,305],[1310,425],[1310,680],[1035,590],[660,555],[305,505],[260,745],[565,840],[880,900],[1220,925]];
const route=[[-250,345],[70,345],...stumpPositions.map(([x,y],i)=>[x+(i>=4&&i<=7?105:-105),y+76]),[1460,975]];
const cumulative=[0];for(let i=1;i<route.length;i++)cumulative.push(cumulative[i-1]+Math.hypot(route[i][0]-route[i-1][0],route[i][1]-route[i-1][1]));
const stops=cumulative.slice(2,14);
const LEVELS={1:{name:'Обычный',speed:32},2:{name:'Продвинутый',speed:50}};
let selectedLevel=1,speed=LEVELS[1].speed;
function pointAt(d){d=Math.max(0,Math.min(d,cumulative.at(-1)));let i=1;while(cumulative[i]<d)i++;const f=(d-cumulative[i-1])/(cumulative[i]-cumulative[i-1]);return {x:route[i-1][0]+(route[i][0]-route[i-1][0])*f,y:route[i-1][1]+(route[i][1]-route[i-1][1])*f,left:route[i][0]<route[i-1][0]};}
const images={};let assetsReady=false,loadFailure=false;
Promise.all(['forest','characters','children'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[name]=im;resolve();};im.onerror=reject;im.src=`assets/${name}.png`;}))).then(()=>{assetsReady=true;welcome();}).catch(()=>{loadFailure=true;$('dialog').innerHTML='<h1>Не удалось загрузить картинки</h1><p>Открой index.html вместе с папкой assets.</p>';});
let state='menu',round=makeRound(),index=0,errors=0,elapsed=0,beaver=stops[0],fox=beaver-390,lock=0,mode='',transition=null,particles=[],last=performance.now(),lastFoxSound=0,pausedFrom=null,result=null;
let audio=null,muted=false,musicTimer=null,musicStep=0;
function initAudio(){if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=new AC();}if(audio.state==='suspended')audio.resume();if(!musicTimer)musicTimer=setInterval(musicTick,240);}
function tone(freq,duration=.12,volume=.08,type='sine',delay=0){if(!audio||muted)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+duration+.02);}
function sound(kind){if(kind==='click')tone(720,.07,.045,'triangle');if(kind==='wrong'){tone(240,.18,.07,'triangle');tone(175,.24,.07,'triangle',.12);}if(kind==='gnaw'){for(let i=0;i<5;i++)tone(i%2?420:620,.045,.06,'square',i*.08);tone(1046,.2,.06,'sine',.35);}if(kind==='fox'){tone(155,.07,.03,'sawtooth');tone(190,.07,.03,'sawtooth',.1);}if(kind==='win')[523,659,784,1046,784,1046].forEach((f,i)=>tone(f,i===5?.65:.22,.1,'triangle',i*.16));if(kind==='lose')[392,330,262,196].forEach((f,i)=>tone(f,.3,.07,'triangle',i*.2));}
function musicTick(){if(state!=='playing'||muted||document.hidden)return;const melody=[72,76,79,76,74,77,81,77,72,76,79,84,81,79,76,74,69,72,76,72,71,74,77,74,67,71,74,79,76,74,71,67];const note=melody[musicStep%melody.length];tone(440*2**((note-69)/12),.2,.025,'sine');if(musicStep%4===0)tone(130.81*([1,4/3,1,1.5][Math.floor(musicStep/8)%4]),.65,.019,'triangle');if(musicStep%16===9){tone(1800,.09,.014);tone(2300,.08,.012,'sine',.12);}musicStep++;}
function showDialog(html){$('overlay').classList.remove('hidden');$('dialog').innerHTML=html;requestAnimationFrame(()=>$('dialog').querySelector('button')?.focus());}
const mascot=type=>`<div class="mascot ${type||''}" role="img" aria-label="Бобр"></div>`;
function welcome(){state='menu';pausedFrom=null;showDialog(`<div class="subtitle">A woodland adventure</div><h1>Бобр и лиса</h1>${mascot()}<p>Привет! Поможешь мне пройти лесную тропинку?<br>Выбирай слова, стачивай пеньки<br>и не дай лисе нас догнать!</p><div class="level-picker" role="group" aria-label="Выбор уровня"><p class="level-label">Выбери уровень</p><div class="level-options"><button class="level-option ${selectedLevel===1?'selected':''}" data-action="level1" aria-pressed="${selectedLevel===1}"><strong>1 · Обычный</strong><small>Знакомая лесная погоня</small></button><button class="level-option ${selectedLevel===2?'selected':''}" data-action="level2" aria-pressed="${selectedLevel===2}"><strong>2 · Продвинутый</strong><small>Лиса заметно быстрее!</small></button></div></div><div class="buttons"><button class="wood-button" data-action="play" ${assetsReady?'':'disabled'}>Play ▶</button><button class="wood-button secondary" data-action="instructions">Инструкция</button></div>`);}
function instructions(){if(state==='playing'){pausedFrom='playing';state='paused';}else pausedFrom='menu';showDialog(`<div class="subtitle">Маленькая лесная подсказка</div><h1>Помоги бобру!</h1>${mascot('explain')}<ol class="rules"><li>Прочитай русское предложение и посмотри на картинку.</li><li>Выбери слово для пропуска в английском предложении.</li><li>Верный ответ — бобр стачивает пенёк и идёт дальше!</li><li>Не медли: лиса идёт следом. Шестая ошибка или встреча с лисой — проигрыш.</li><li>Пройди все 12 пеньков, и мы победим!</li></ol><div class="pronouns"><div>👦 его<b>his</b></div><div>👧 её<b>her</b></div><div>👫 их<b>their</b></div><div>🙋 мой / моя / моё<b>my</b></div><div>👫 наш / наша / наше<b>our</b></div><div>👉 твой / твоя / твоё<b>your</b></div></div><p class="paused-note">В заданиях слова могут быть «мой», «моя», «моё» — по-английски это всегда my.${pausedFrom==='playing'?'<br>Пока открыта инструкция, погоня на паузе.':''}</p><div class="buttons" style="justify-content:flex-end"><button class="wood-button" data-action="ok">Ok ✓</button></div>`);}
function start(){speed=LEVELS[selectedLevel].speed;document.querySelectorAll('.confetti').forEach(e=>e.remove());round=makeRound();state='playing';index=0;errors=0;elapsed=0;beaver=stops[0];fox=beaver-390;lock=0;transition=null;particles=[];mode='';result=null;lastFoxSound=0;musicStep=0;$('overlay').classList.add('hidden');$('board-note').textContent='Лиса идёт по пятам — выбирай слово!';renderTask();updateHud();}
function renderTask(){const t=round[index];$('task-count').textContent=`ПЕНЁК ${index+1} ИЗ 12`;$('russian').textContent=t.russian;$('english').innerHTML=t.english.replace('__','<span class="blank">?</span>');$('feedback').textContent='Какое слово пропущено?';$('answers').innerHTML=t.choices.map((p,i)=>`<button class="answer" data-answer="${p}" aria-label="${p}, вариант ${i+1}">${p}</button>`).join('');}
function answer(value){if(state!=='playing'||lock>0||transition)return;const t=round[index];const btn=[...$('answers').children].find(b=>b.dataset.answer===value);if(!btn)return;sound('click');if(value!==t.pronoun){errors++;sound('wrong');btn.classList.add('wrong');$('feedback').textContent='Попробуй ещё! Лиса всё ближе…';lock=.55;mode='wrong';if(errors>=6)finish(false,'You made 6 mistakes. Let’s try again!');}else{sound('gnaw');btn.classList.add('correct');$('feedback').textContent='Верно! Хрум-хрум — и вперёд!';lock=.68;mode='gnaw';}for(const b of $('answers').children)b.disabled=true;updateHud();}
function gnawed(){const [x,y]=stumpPositions[index];for(let i=0;i<24;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:-70-Math.random()*170,age:0,life:.6+Math.random()*.7});index++;if(index===12){finish(true);return;}transition={from:beaver,to:stops[index],age:0,duration:.72};mode='walk';}
function finish(win,reason=''){if(state!=='playing')return;state=win?'won':'lost';lock=0;transition=null;mode=win?'happy':'retry';result={win,time:elapsed,errors,score:win?Math.max(100,Math.round(12000-elapsed*45-errors*1100)):0};let best=0;try{best=Number(localStorage.getItem('beaver-best'))||0;if(win&&result.score>best){best=result.score;localStorage.setItem('beaver-best',String(best));}}catch{}sound(win?'win':'lose');if(!win&&reason.includes('fox'))sound('fox');for(const b of $('answers').children)b.disabled=true;showDialog(`<div class="subtitle">${win?'Forest mission complete':'Another adventure awaits'}</div><h1>${win?'Great job! You win!':'Let’s try again!'}</h1>${mascot(win?'happy':'retry')}<p>${win?'You saved the beaver!<br>All 12 stumps are gone. Well done!':reason}</p><div class="stats"><div>Time<b>${formatTime(elapsed)}</b></div><div>Mistakes<b>${errors} / 6</b></div><div>Score<b>${result.score.toLocaleString('en-US')}</b></div></div>${win?`<p class="best">Best score: ${best.toLocaleString('en-US')} · Faster + fewer mistakes = more points!</p>`:''}<div class="buttons"><button class="wood-button" data-action="play">Play again ↻</button><button class="wood-button secondary" data-action="exit">Exit ↗</button></div>`);if(win)celebrate();}
function celebrate(){const icons=[...round.map(t=>t.word[4]),'🪵','🍄','🌿','🍂','🌰'];for(let i=0;i<45;i++){const el=document.createElement('span');el.className='confetti';el.textContent=icons[i%icons.length];el.style.left=`${Math.random()*100}%`;el.style.animationDuration=`${5+Math.random()*5}s`;el.style.animationDelay=`${Math.random()*3}s`;el.style.setProperty('--drift',`${(Math.random()-.5)*220}px`);document.body.append(el);el.addEventListener('animationend',()=>el.remove());}}
function exit(){state='exit';document.querySelectorAll('.confetti').forEach(e=>e.remove());if(audio)audio.suspend();showDialog(`<h1>See you in the forest!</h1>${mascot()}<p>Игра завершена. Теперь можно закрыть вкладку.<br>До новых лесных приключений!</p><div class="buttons"><button class="wood-button" data-action="menu">Back to menu</button></div>`);}
function formatTime(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function updateHud(){$('progress').textContent=`🪵 ${index} / 12`;$('time').textContent=`⏱ ${formatTime(elapsed)}`;$('errors').textContent=`Ошибки: ${errors} / 6`;$('errors').style.color=errors>=4?'#ffd0a4':'';$('distance').style.width=`${Math.min(100,Math.max(0,(beaver-fox)/700*100))}%`;}
function tick(dt){if(state!=='playing')return;elapsed+=dt;fox+=speed*dt;if(transition){transition.age+=dt;const f=Math.min(1,transition.age/transition.duration);beaver=transition.from+(transition.to-transition.from)*(f*f*(3-2*f));if(f===1){transition=null;mode='';renderTask();}}if(fox>=beaver){finish(false,'The fox caught up! Let’s try again!');return;}if(lock>0){lock=Math.max(0,lock-dt);if(lock===0){if(mode==='gnaw')gnawed();else{mode='';for(const b of $('answers').children)b.disabled=false;}}}if(elapsed-lastFoxSound>7){lastFoxSound=elapsed;sound('fox');}updateHud();}
function sprite(img,col,row,cols,rows,x,y,w,h,flip=false){if(!img)return;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);const stump=img===images.characters&&col===2&&row===1;ctx.drawImage(img,stump?img.width*.7096:col*img.width/cols,stump?img.height*.5469:row*img.height/rows,stump?img.width*.2904:img.width/cols,stump?img.height*.4336:img.height/rows,-w/2,-h,w,h);ctx.restore();}
function draw(now){ctx.clearRect(0,0,1536,1024);if(images.forest)ctx.drawImage(images.forest,0,0,1536,1024);else{ctx.fillStyle='#345b32';ctx.fillRect(0,0,1536,1024);}if(!assetsReady)return;
 ctx.save();ctx.lineWidth=5;ctx.strokeStyle='#835c2d66';ctx.setLineDash([10,18]);ctx.beginPath();route.slice(1).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.restore();
 for(let i=index;i<12;i++){const [x,y]=stumpPositions[i],t=round[i],active=i===index;ctx.save();if(active){ctx.shadowColor='#fff2a0';ctx.shadowBlur=22;}if(active&&mode==='gnaw'){ctx.translate(x,y);ctx.rotate(Math.sin(now*.05)*.035);ctx.translate(-x,-y);}sprite(images.characters,2,1,3,2,x,y+80,252,230);ctx.shadowBlur=0;sprite(images.children,t.child%2,Math.floor(t.child/2),2,2,x+7,y+56,160,145);ctx.font='48px "Segoe UI Emoji",sans-serif';ctx.textAlign='center';ctx.fillText(t.word[4],x+8,y+44);ctx.fillStyle='#ffe2a3';ctx.strokeStyle='#6c3d1e';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x-82,y-56,22,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#5a351f';ctx.font='bold 27px Trebuchet MS';ctx.fillText(String(i+1),x-82,y-46);if(active){ctx.fillStyle='#fff0a4';ctx.font='bold 24px Trebuchet MS';ctx.fillText('▼',x,y-147+Math.sin(now*.004)*5);}ctx.restore();}
 const f=pointAt(fox),b=pointAt(beaver);ctx.save();ctx.fillStyle='#0003';for(const p of [f,b]){ctx.beginPath();ctx.ellipse(p.x,p.y+3,55,12,0,0,Math.PI*2);ctx.fill();}ctx.restore();sprite(images.characters,1,1,3,2,f.x,f.y+Math.sin(now*.013)*4,210,190,f.left);
 let col=mode==='happy'?2:0,row=mode==='retry'?1:0;const bob=mode==='gnaw'?Math.sin(now*.055)*7:transition?Math.sin(now*.024)*5:Math.sin(now*.003)*2;sprite(images.characters,col,row,3,2,b.x,b.y+bob,180,180,b.left);
 if(state==='playing'&&elapsed-lastFoxSound<.6){ctx.font='26px Segoe UI Emoji';ctx.fillText('👅',f.x+(f.left?-45:45),f.y-62);}
 for(const p of particles){ctx.save();ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.translate(p.x,p.y);ctx.rotate(p.age*6);ctx.fillStyle='#e9bf74';ctx.fillRect(-5,-3,10,6);ctx.restore();}}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;tick(dt);for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=320*dt;}particles=particles.filter(p=>p.age<p.life);draw(now);requestAnimationFrame(frame);}
$('dialog').addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;initAudio();sound('click');if((action==='level1'||action==='level2')&&state==='menu'){selectedLevel=Number(action.slice(-1));welcome();dialog.querySelector('[data-action='+action+']').focus();}if(action==='play')start();if(action==='instructions')instructions();if(action==='ok'){if(pausedFrom==='playing'){state='playing';pausedFrom=null;$('overlay').classList.add('hidden');}else welcome();}if(action==='exit')exit();if(action==='menu')welcome();});
$('answers').addEventListener('click',e=>{const value=e.target.closest('[data-answer]')?.dataset.answer;if(value)answer(value);});
$('sound').addEventListener('click',()=>{initAudio();muted=!muted;if(!muted)sound('click');$('sound').textContent=muted?'♪̸':'♫';$('sound').setAttribute('aria-label',muted?'Включить звук':'Выключить звук');});
$('help').addEventListener('click',()=>{initAudio();sound('click');if(state==='playing'||state==='menu')instructions();});
$('home').addEventListener('click',()=>{initAudio();sound('click');document.querySelectorAll('.confetti').forEach(e=>e.remove());index=0;beaver=stops[0];fox=beaver-390;errors=0;elapsed=0;transition=null;mode='';welcome();updateHud();});
document.addEventListener('keydown',e=>{if(state==='playing'&&['1','2','3'].includes(e.key)){e.preventDefault();answer(round[index].choices[Number(e.key)-1]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'){state='paused';pausedFrom='playing';showDialog(`<h1>Приключение на паузе</h1>${mascot()}<p>Бобр и лиса ждут твоего возвращения.</p><div class="buttons"><button class="wood-button" data-action="ok">Продолжить ▶</button></div>`);}});
showDialog('<h1>Готовим лесную тропинку…</h1><p>Загружаем бобра, лису и пеньки.</p>');requestAnimationFrame(frame);



