const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const root=__dirname,port=9341,delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const browser=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check',`--remote-debugging-port=${port}`,`--user-data-dir=${path.join(root,'.browser-check')}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let ws;try{
 let tabs;for(let i=0;i<50;i++){try{tabs=await(await fetch(`http://127.0.0.1:${port}/json`)).json();break;}catch{await delay(200);}}
 if(!tabs)throw Error('Browser unavailable');ws=new WebSocket(tabs[0].webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let next=0;const pending=new Map(),errors=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 const assert=(condition,label)=>{if(!condition)throw Error(label);console.log('PASS '+label);};
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'file:///'+root.replaceAll('\\','/')+'/'+(process.argv[2]||'index.html')});await delay(500);for(let i=0;i<50;i++){if(await ev('typeof assetsReady!=="undefined" && assetsReady'))break;await delay(150);}
 console.log(await ev('JSON.stringify({url:location.href,body:document.body.innerText.slice(0,250),scripts:[...document.scripts].map(s=>s.src)})'));assert(await ev('assetsReady'),'all game images load');await delay(200);let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'menu-check.png'),Buffer.from(shot.data,'base64'));
 assert(await ev(`(()=>{for(let j=0;j<300;j++){const r=makeRound();if(r.length!==12||r.filter(t=>t.count===1).length!==7||r.filter(t=>t.count===2).length!==5||new Set(r.map(t=>t.word[0])).size!==12||new Set(r.map(t=>t.pronoun)).size!==6||r.some(t=>t.choices.length!==3||new Set(t.choices).size!==3||!t.choices.includes(t.pronoun)))return false;}return WORDS.length===24;})()`),'300 rounds: 7 singles, 5 pairs, 12 distinct objects, six pronouns, valid answers');
 assert(await ev(`(()=>{muted=true;welcome();const options=[...document.querySelectorAll('.level-option')];if(options.length!==2||options[0].getAttribute('aria-pressed')!=='true')return false;document.querySelector('[data-action="play"]').click();let f=fox;tick(1);if(speed!==32||Math.abs(fox-f-32)>1e-6)return false;welcome();document.querySelector('[data-action="level2"]').click();if(selectedLevel!==2||document.querySelector('[data-action="level2"]').getAttribute('aria-pressed')!=='true')return false;instructions();document.querySelector('[data-action="ok"]').click();if(selectedLevel!==2)return false;document.querySelector('[data-action="play"]').click();f=fox;tick(1);if(speed!==50||Math.abs(fox-f-50)>1e-6)return false;finish(false,'Test');document.querySelector('[data-action="play"]').click();if(speed!==50||selectedLevel!==2)return false;welcome();document.querySelector('[data-action="level1"]').click();start();tick(8);if(state!=='playing')return false;welcome();document.querySelector('[data-action="level2"]').click();start();tick(8);if(state!=='lost')return false;welcome();document.querySelector('[data-action="level1"]').click();return true;})()`),'menu level selection, 32/50 speeds, instructions and replay retain level, advanced catches sooner');
 await ev('muted=true;start()');await delay(100);shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'gameplay-check.png'),Buffer.from(shot.data,'base64'));
 assert(await ev(`(()=>{for(let i=0;i<6;i++){answer(round[index].choices.find(p=>p!==round[index].pronoun));if(i<5)tick(.56);}return state==='lost'&&errors===6&&index===0;})()`),'sixth mistake loses without clearing stump');
 assert(await ev(`(()=>{start();fox=beaver-1;tick(.1);return state==='lost'&&errors===0;})()`),'fox catching beaver loses');
 assert(await ev(`(()=>{start();answer(round[0].pronoun);const e=errors;answer('invalid');tick(.7);return index===1&&errors===e&&!!transition;})()`),'correct answer clears one stump and locks repeated clicks');
 assert(await ev(`(()=>{start();for(let i=0;i<5;i++){answer(round[index].choices.find(p=>p!==round[index].pronoun));tick(.56);}for(let i=0;i<12;i++){answer(round[index].pronoun);tick(.7);if(state==='playing')tick(.73);}return state==='won'&&index===12&&errors===5&&result.score>0;})()`),'12 cleared stumps and five mistakes wins');
 shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'win-check.png'),Buffer.from(shot.data,'base64'));
 assert(await ev(`(()=>{start();return index===0&&errors===0&&elapsed===0&&state==='playing'&&!transition&&fox<beaver;})()`),'restart resets game');
 assert(await ev(`(()=>{instructions();const f=fox,t=elapsed;tick(10);return state==='paused'&&fox===f&&elapsed===t;})()`),'instructions pause chase');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await ev(`welcome();start()`);await delay(150);shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'mobile-check.png'),Buffer.from(shot.data,'base64'));
 assert(await ev('document.documentElement.scrollWidth<=390'),'mobile page fits viewport');assert(!errors.length,'no browser runtime exceptions');
 }finally{if(ws)ws.close();browser.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});




